spring:
  application:
    name: @pom.artifactId@
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sso?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework.security.oauth2: debug
    org.springframework: debug